### ISSUE TITLE
启动命令报错

### ISSUE THREAD

**Issue by Echocf** [netless-io/react-whiteboard#7]
按照您的readme操作作完后到了本地启动的一步，但是报错是start命令找不到。
`D:\公司文件\uniApp\myBoard\react-whiteboard\whiteboard>yarn start
yarn run v1.22.5
warning package.json: No license field
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.`

**Comment by alwaysmavs** [comment]
已经修改文档，请重新按文档测试一下
